-- ============================================================================
-- NUSA KASIR — Midtrans Payment Integration Migration
-- ============================================================================
-- Adds:
--   1. payments table (track Midtrans order status)
--   2. order_id + package columns on licenses table
--   3. Updated can_activate() with order_id support
-- ============================================================================

-- Payments table — tracks every Midtrans transaction
create table if not exists payments (
  id           bigint generated by default as identity primary key,
  order_id     text unique not null,
  google_id    text not null,
  product      text not null,
  package      text not null check (package in ('1bulan', 'lifetime')),
  amount       integer not null,
  status       text not null default 'pending',
  snap_token   text,
  license_key  text,
  created_at   timestamptz default now(),
  updated_at   timestamptz default now()
);

create index if not exists idx_payments_order_id on payments(order_id);
create index if not exists idx_payments_google_id on payments(google_id);

-- Add order_id + package columns to licenses
alter table licenses add column if not exists order_id text;
alter table licenses add column if not exists package text check (package in ('1bulan', 'lifetime'));

create index if not exists idx_licenses_order_id on licenses(order_id);

-- Update can_activate(): also check order_id duplicate (shouldn't happen, safety net)
-- The existing function from 0005 is fine — no schema changes needed.
