-- ============================================================================
-- NUSA KASIR — Toko Online Ekstra (Rilis Besar v2.2.23)
-- Kolom baru + tabel baru untuk fitur online store yang diadaptasi dari
-- proyek GAS (Dimsum Sewu): metode bayar dinamis, ambil/delivery, membership
-- & poin, ajak teman (referral), kupon online, cabang dengan WA per cabang.
--
-- Semua statement idempotent (IF NOT EXISTS) — aman dijalankan ulang.
-- Run: supabase db push (dari repo nusa-online — jangan dari nusa_kasir!)
-- ============================================================================

-- ── 1. store_settings: konfigurasi tambahan (JSON) ──────────────────
ALTER TABLE public.store_settings
  ADD COLUMN IF NOT EXISTS order_types    TEXT DEFAULT NULL, -- JSON: [{name,is_active}]
  ADD COLUMN IF NOT EXISTS delivery_fee   INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pickup_options TEXT DEFAULT NULL, -- JSON: [{time,is_active}]
  ADD COLUMN IF NOT EXISTS payment_methods TEXT DEFAULT NULL, -- JSON: [{name,type,details,qr,handling_fee,is_active}]
  ADD COLUMN IF NOT EXISTS member_settings TEXT DEFAULT NULL; -- JSON: {pointsPerRupiah,minRedeem,referralPercent,referralBonus,...}

-- ── 2. promos: kupon / promo online (disinkron dari app) ──────────
CREATE TABLE IF NOT EXISTS public.promos (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id     TEXT NOT NULL,
  code         TEXT NOT NULL,
  title        TEXT DEFAULT '',
  type         TEXT DEFAULT 'persen',   -- persen | nominal
  value        INTEGER DEFAULT 0,
  min_spend    INTEGER DEFAULT 0,
  quota        INTEGER,
  limit_per_user INTEGER,
  start_date   TEXT,
  end_date     TEXT,
  is_active    BOOLEAN DEFAULT true,
  created_at   TIMESTAMPTZ DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_promos_store_code
  ON public.promos(store_id, code);

-- ── 3. online_orders: kolom tambahan order ─────────────────────────
ALTER TABLE public.online_orders
  ADD COLUMN IF NOT EXISTS order_type      TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS used_points     INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS used_promo_id   BIGINT REFERENCES public.promos(id),
  ADD COLUMN IF NOT EXISTS promo_discount  INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS referred_by     TEXT DEFAULT '';

-- ── 4. online_customers: pelanggan toko online (membership & poin) ──
CREATE TABLE IF NOT EXISTS public.online_customers (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id    TEXT NOT NULL,
  name        TEXT NOT NULL DEFAULT '',
  phone       TEXT NOT NULL,           -- tersimpan NORMALISASI 08xx (anti-dobel)
  total_spent INTEGER NOT NULL DEFAULT 0,
  points      INTEGER NOT NULL DEFAULT 0,
  level       TEXT NOT NULL DEFAULT 'Silver',
  promo_history JSONB DEFAULT '[]'::jsonb, -- {promo_id, used_at}
  referred_by TEXT DEFAULT '',         -- phone referrer (ternormalisasi 08xx)
  created_at  TIMESTAMPTZ DEFAULT now(),
  updated_at  TIMESTAMPTZ DEFAULT now()
);

-- Unik per (store_id, phone ternormalisasi) → "Adi"/"adi" = 1 pelanggan
CREATE UNIQUE INDEX IF NOT EXISTS idx_online_customers_store_phone
  ON public.online_customers(store_id, phone);
CREATE INDEX IF NOT EXISTS idx_online_customers_store
  ON public.online_customers(store_id);

-- ── 4. branches: cabang toko online (dengan WA per cabang) ─────────
CREATE TABLE IF NOT EXISTS public.branches (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id  TEXT NOT NULL,
  name      TEXT NOT NULL,
  phone     TEXT DEFAULT '',          -- WA tujuan per cabang (08xx)
  is_active BOOLEAN NOT NULL DEFAULT true,
  sort      INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_branches_store_name
  ON public.branches(store_id, name);

-- ── 5. RLS ─────────────────────────────────────────────────────────
-- online_customers: publik boleh baca (buat lookup anti-dobel di
-- submit_order) & insert (order baru). Update via service role edge.
ALTER TABLE public.promos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.online_customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.branches ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_read_promos" ON public.promos;
CREATE POLICY "anon_read_promos"
  ON public.promos FOR SELECT USING (true);

DROP POLICY IF EXISTS "anon_read_online_customers" ON public.online_customers;
CREATE POLICY "anon_read_online_customers"
  ON public.online_customers FOR SELECT USING (true);

DROP POLICY IF EXISTS "anon_insert_online_customers" ON public.online_customers;
CREATE POLICY "anon_insert_online_customers"
  ON public.online_customers FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "anon_read_branches" ON public.branches;
CREATE POLICY "anon_read_branches"
  ON public.branches FOR SELECT USING (true);
